### ISSUE TITLE
Is there a way to enable latex code for 2D Animation in Blender

### ISSUE THREAD

**Issue by akashe** [ghseeli/latex2blender#3]
I want to make an educational 2D animation on Nueral Networks using Blender. To do so, I would need latex equations in the animation. latex2blender works fine for 3D environment. Is there a way to do so for 2D also?

**Comment by peterkj1** [comment]
If you go to file->new->2D Animation, then go into object mode (click the top left button that says draw and you should see the object mode option) and press "n" to open up the properties menu, you should see the latex2blender add-on which you can then use in the 2D animation window. You will probably want to change the x rotation to 90 deg. in the latex2blender panel so that the text is aligned with the default camera view when rendered.

**Comment by akashe** [comment]
Thanks for the quick reply.
